import type { Field } from '@/types'

export const MOCK_FIELDS: Field[] = [
  {
    id: 'mock-1',
    owner_id: 'owner-1',
    name: 'ملعب النجوم',
    description: 'ملعب حديث بعشب صناعي عالي الجودة في قلب الدار البيضاء',
    address: '12 شارع محمد الخامس، المعاريف',
    city: 'الدار البيضاء',
    phone: '+212661234567',
    opening_hours: { default: { open: '08:00', close: '00:00' } },
    is_active: true,
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
    avg_rating: 4.6,
    pitches: [
      {
        id: 'pitch-1a',
        field_id: 'mock-1',
        name: 'الملعب الصغير 1',
        type: '5v5',
        price_per_hour: 200,
        slot_duration_minutes: 60,
        allow_pay_at_field: true,
        allow_online_payment: false,
        is_active: true,
      },
      {
        id: 'pitch-1b',
        field_id: 'mock-1',
        name: 'الملعب المتوسط',
        type: '7v7',
        price_per_hour: 350,
        slot_duration_minutes: 60,
        allow_pay_at_field: true,
        allow_online_payment: true,
        is_active: true,
      },
    ],
    field_photos: [
      {
        id: 'photo-1a',
        field_id: 'mock-1',
        storage_url: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800&q=80',
        is_cover: true,
        sort_order: 0,
      },
      {
        id: 'photo-1b',
        field_id: 'mock-1',
        storage_url: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&q=80',
        is_cover: false,
        sort_order: 1,
      },
      {
        id: 'photo-1c',
        field_id: 'mock-1',
        storage_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
    reviews: [
      {
        id: 'review-1a',
        booking_id: 'booking-x',
        player_id: 'player-1',
        field_id: 'mock-1',
        rating: 5,
        comment: 'ملعب رائع وخدمة ممتازة، سنعود حتماً!',
        created_at: '2024-11-15T14:00:00Z',
        player: {
          id: 'player-1',
          email: null,
          phone: '+212600000001',
          full_name: 'يوسف الأمراني',
          role: 'player',
          preferred_language: 'ar',
          created_at: '2024-01-01T00:00:00Z',
        },
      },
      {
        id: 'review-1b',
        booking_id: 'booking-y',
        player_id: 'player-2',
        field_id: 'mock-1',
        rating: 4,
        comment: 'Terrain propre, vestiaires corrects. Je recommande.',
        created_at: '2024-11-10T18:00:00Z',
        player: {
          id: 'player-2',
          email: null,
          phone: '+212600000002',
          full_name: 'Karim Benali',
          role: 'player',
          preferred_language: 'fr',
          created_at: '2024-01-01T00:00:00Z',
        },
      },
    ],
  },
  {
    id: 'mock-2',
    owner_id: 'owner-2',
    name: 'ملعب الأطلس',
    description: 'ملعب كبير مناسب للمباريات الرسمية',
    address: '45 طريق الجديدة، عين السبع',
    city: 'الدار البيضاء',
    phone: '+212662345678',
    opening_hours: { default: { open: '09:00', close: '23:00' } },
    is_active: true,
    is_featured: false,
    created_at: '2024-02-01T00:00:00Z',
    avg_rating: 4.2,
    pitches: [
      {
        id: 'pitch-2a',
        field_id: 'mock-2',
        name: 'ملعب 7 في 7',
        type: '7v7',
        price_per_hour: 300,
        slot_duration_minutes: 60,
        allow_pay_at_field: true,
        allow_online_payment: false,
        is_active: true,
      },
      {
        id: 'pitch-2b',
        field_id: 'mock-2',
        name: 'الملعب الكبير',
        type: '11v11',
        price_per_hour: 600,
        slot_duration_minutes: 90,
        allow_pay_at_field: true,
        allow_online_payment: true,
        is_active: true,
      },
    ],
    field_photos: [
      {
        id: 'photo-2a',
        field_id: 'mock-2',
        storage_url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
        is_cover: true,
        sort_order: 0,
      },
      {
        id: 'photo-2b',
        field_id: 'mock-2',
        storage_url: 'https://images.unsplash.com/photo-1589487391730-58f20eb2c308?w=800&q=80',
        is_cover: false,
        sort_order: 1,
      },
    ],
    reviews: [
      {
        id: 'review-2a',
        booking_id: 'booking-z',
        player_id: 'player-3',
        field_id: 'mock-2',
        rating: 4,
        comment: 'ملعب جيد، الأسعار معقولة.',
        created_at: '2024-10-20T16:00:00Z',
        player: {
          id: 'player-3',
          email: null,
          phone: '+212600000003',
          full_name: 'عمر الزياني',
          role: 'player',
          preferred_language: 'ar',
          created_at: '2024-01-01T00:00:00Z',
        },
      },
    ],
  },
  {
    id: 'mock-3',
    owner_id: 'owner-3',
    name: 'ملعب الحسنى',
    description: 'ملاعب للجميع في قلب الرباط',
    address: '8 زنقة الزعتر، أكدال',
    city: 'الرباط',
    phone: '+212663456789',
    opening_hours: { default: { open: '07:00', close: '23:00' } },
    is_active: true,
    is_featured: true,
    created_at: '2024-03-01T00:00:00Z',
    avg_rating: 4.8,
    pitches: [
      {
        id: 'pitch-3a',
        field_id: 'mock-3',
        name: 'ملعب ميني 5',
        type: '5v5',
        price_per_hour: 180,
        slot_duration_minutes: 60,
        allow_pay_at_field: true,
        allow_online_payment: true,
        is_active: true,
      },
      {
        id: 'pitch-3b',
        field_id: 'mock-3',
        name: 'ملعب 6 في 6',
        type: '6v6',
        price_per_hour: 250,
        slot_duration_minutes: 60,
        allow_pay_at_field: true,
        allow_online_payment: true,
        is_active: true,
      },
    ],
    field_photos: [
      {
        id: 'photo-3a',
        field_id: 'mock-3',
        storage_url: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&q=80',
        is_cover: true,
        sort_order: 0,
      },
      {
        id: 'photo-3b',
        field_id: 'mock-3',
        storage_url: 'https://images.unsplash.com/photo-1614632537190-23e4146777db?w=800&q=80',
        is_cover: false,
        sort_order: 1,
      },
      {
        id: 'photo-3c',
        field_id: 'mock-3',
        storage_url: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
    reviews: [
      {
        id: 'review-3a',
        booking_id: 'booking-w',
        player_id: 'player-4',
        field_id: 'mock-3',
        rating: 5,
        comment: 'أفضل ملعب في الرباط! نظيف ومنظم.',
        created_at: '2024-12-01T10:00:00Z',
        player: {
          id: 'player-4',
          email: null,
          phone: '+212600000004',
          full_name: 'سمية الحيوني',
          role: 'player',
          preferred_language: 'ar',
          created_at: '2024-01-01T00:00:00Z',
        },
      },
      {
        id: 'review-3b',
        booking_id: 'booking-v',
        player_id: 'player-5',
        field_id: 'mock-3',
        rating: 5,
        comment: 'Super terrain, staff très accueillant!',
        created_at: '2024-11-28T19:00:00Z',
        player: {
          id: 'player-5',
          email: null,
          phone: '+212600000005',
          full_name: 'Nadia Tahiri',
          role: 'player',
          preferred_language: 'fr',
          created_at: '2024-01-01T00:00:00Z',
        },
      },
    ],
  },
  {
    id: 'mock-4',
    owner_id: 'owner-4',
    name: 'ملعب طارق',
    description: 'ملعب حديث في مراكش الحمراء',
    address: '22 شارع القادسية، جليز',
    city: 'مراكش',
    phone: '+212664567890',
    opening_hours: { default: { open: '10:00', close: '22:00' } },
    is_active: true,
    is_featured: false,
    created_at: '2024-04-01T00:00:00Z',
    avg_rating: 3.9,
    pitches: [
      {
        id: 'pitch-4a',
        field_id: 'mock-4',
        name: 'الملعب الأساسي',
        type: '7v7',
        price_per_hour: 280,
        slot_duration_minutes: 60,
        allow_pay_at_field: true,
        allow_online_payment: false,
        is_active: true,
      },
    ],
    field_photos: [
      {
        id: 'photo-4a',
        field_id: 'mock-4',
        storage_url: 'https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?w=800&q=80',
        is_cover: true,
        sort_order: 0,
      },
    ],
    reviews: [
      {
        id: 'review-4a',
        booking_id: 'booking-u',
        player_id: 'player-6',
        field_id: 'mock-4',
        rating: 4,
        comment: 'Bien mais vestiaires à améliorer.',
        created_at: '2024-10-05T14:00:00Z',
        player: {
          id: 'player-6',
          email: null,
          phone: '+212600000006',
          full_name: 'Hassan Ouali',
          role: 'player',
          preferred_language: 'fr',
          created_at: '2024-01-01T00:00:00Z',
        },
      },
    ],
  },
]
